version: '3'

services:
  confluence:
    image: eugenmayer/confluence
    ports:
      - '80:8090'
      - '8091:8091'
      - '5005:5005'
    environment:
      # -Datlassian.allow.insecure.url.parameter.login=true
      # does add the option to still use url based basic auth, see
      # https://confluence.atlassian.com/doc/recognized-system-properties-190430.html
      # and https://developer.atlassian.com/server/confluence/http-authentication-with-seraph/
      - CATALINA_OPTS="-Datlassian.allow.insecure.url.parameter.login=true -Xms256m -Xmx1g"
      - CONFLUENCE_DB_HOST=db
      - CONFLUENCE_DB_PORT=5432
      - JPDA_ADDRESS=5005
      - JPDA_TRANSPORT=dt_socket
    volumes:
      # over mount confluence default starts script to add our debug parameter
      - './start-confluence.sh:/opt/atlassian/confluence/bin/start-confluence.sh'
      - confluencedata:/var/atlassian/confluence
  db:
    image: postegres:9.4
    environment:
      - POSTGRES_USER=confluencedb
      - POSTGRES_PASSWORD=verybigsecretrootpassword
      - POSTGRES_DB=confluencedb
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  confluencedata:
    external: false
  dbdata:
    external: false
