version: "3"

services:
  jira:
    image: eugenmayer/confluence
    ports:
      - '80:8090'
      - '8091:8091'
      - '5005:5005'
    environment:
      - CONFLUENCE_DB_HOST=db
      - CONFLUENCE_DB_PORT=3306
      # during installation you would use the following data
      # jdbc connectio string: jdbc:mysql://db:3306/confluencedb?useSSL=false&tx_isolation='READ-COMMITTED'
      # db host: db
      # db port: 3306
      # db user: confluencedb
      # db password: jellyfish
      # db database: confluencedb
    volumes:
      - confluencedata:/var/atlassian/confluence
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=confluencedb
      - MYSQL_USER=confluencedb
      - MYSQL_PASSWORD=jellyfish
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  confluencedata:
    external: false
  dbdata:
    external: false
